os: linux
dist: trusty
language: python
python:
  - "2.7"

env:
  PLUMED_VERSION=2.2.4
  PLUMED_CONFIG=
  CXX=mpicxx

addons:
  apt:
    packages:
      - environment-modules
      - openmpi-bin
      - libopenmpi-dev
      - liblapack-dev
      - libmatheval-dev

cache:
  directories:
    - $HOME/opt

before_install:
  - PLUMED_PREFIX=$HOME/opt/plumed
  - PLUMED_URL=https://github.com/plumed/plumed2.git
  - PLUMED_SRC=$HOME/src/plumed
  # Enable "module" command
  # See http://askubuntu.com/questions/343692/module-load-command-does-not-work/343721
  - module() { eval `modulecmd bash $*`; }
  # Clone Plumed repository
  - if [ ! -d $PLUMED_PREFIX ]; then
      git clone --branch v$PLUMED_VERSION --depth 1 $PLUMED_URL $PLUMED_SRC;
    fi
  # Configure Plumed
  - if [ -d $PLUMED_SRC ]; then
      cd $PLUMED_SRC &&
      ./configure --prefix=$PLUMED_PREFIX $PLUMED_CONFIG;
    fi
  # Build & intall Plumed
  - if [ -d $PLUMED_SRC ]; then
      make -j 4 &&
      make install;
    fi
  # Load Plumed module
  - module use $PLUMED_PREFIX/lib/plumed
  - module load modulefile
  # Print some information about Plumed
  - plumed info --root --configuration --long-version --git-version
  # Test Plumed
  - if [ -d $PLUMED_SRC ]; then
      make -C regtest &&
      make -C regtest checkfail;
    fi
  # Install MPI4Py
  - pip install mpi4py==2.0.0

install:
  - PYBIAS_SRC=$TRAVIS_BUILD_DIR
  - PYBIAS_BUILD=$HOME/pybias.build
  # Create a build directory
  - mkdir -pv $PYBIAS_BUILD && cd $PYBIAS_BUILD
  # Configure & build PyBias
  - cmake $PYBIAS_SRC
          -DPLUMED_INCLUDE_DIR=$HOME/opt/plumed/include
          -DNUMPY_INCLUDE_DIR=$(python -c 'import numpy; print numpy.get_include()')
          -DMPI4PY_INCLUDE_DIR=$(python -c 'import mpi4py; print mpi4py.get_include()')
  - make VERBOSE=1

script:
  - make test CTEST_OUTPUT_ON_FAILURE=1
